### ISSUE TITLE
impossible to stack after copper heating?

### ISSUE THREAD

**Issue by mymagadsl** [tyronx/vintagecraft#14]
Test production of helmets, found it impossible to stack after copper heating, so you can not build a helmet .. is not BUG?

**Comment by tyronx** [comment]
Hot ingots are only stackable in the anvil or forge (not in player inventory) and only if the temperature difference between the ingots is not larger than 80 degrees.
Making it stackable in player inventory would be very difficult.

Example: Try to put 900 degree copper ingot into anvil, then a 950 degree copper ingot over it - this should work. 

Please let me know if this fixes your problem.

**Comment by mymagadsl** [comment]
This module is great !! thank you very much !!

After the test again, two copper plate 1074 deg, still can not stack

Copper ingot can, but copper plate can not be stacked

**Comment by mymagadsl** [comment]
Copper plate just tested again into the Stone Pot
No heating, direct out after the original Copper plate will become unable to stack

I might put it not clearly, here are pictures
http://imgur.com/a/4Bn3X

**Comment by tyronx** [comment]
Ok, that is a bug. I will fix it, thanks for reporting

**Comment by tyronx** [comment]
Question: Was one copper plate maybe "oddly shaped"?

**Comment by mymagadsl** [comment]
no 
Not oddly shaped

**Comment by tyronx** [comment]
this should be fixed for next version which i will release today or 1-2 days after
