### ISSUE TITLE
vintagecraft causes nei to crash if the tooltip is enabled

### ISSUE THREAD

**Issue by kreezxil** [tyronx/vintagecraft#7]
client crash report: http://paste.ee/p/5SlYh
fml client latest: https://gist.github.com/kreezxil/3ab4735e74f84fc6072f

**Comment by tyronx** [comment]
Please try this again with only the mods vintagecraft and nei installed and repost the crash report again, thanks.

**Comment by kreezxil** [comment]
Some added information. When I turned off the global tooltip function the client stopped crashing.

However, I will do as you suggest later today.

**Comment by kreezxil** [comment]
Ok, I have done it. I just came over some barren terrain into a heavily forested region with many different types of trees generated. The tooltip was on and only your mod and nei was loaded.

client crash report: https://paste.ee/p/L7aJ8
fml client latest: https://paste.ee/p/V60tr
